### ISSUE TITLE
package ‘eva’ is not available (for R version 3.6.2)

### ISSUE THREAD

**Issue by YoannPa** [goncalves-lab/waddR#14]
Hi, 
I tried to install waddR and got an error related to one of its dependency : eva

I am using R version 3.6.2 under Ubuntu 16.04.
It looks like eva is not available anymore in CRAN or Bioconductor since very recently: [https://cran.r-project.org/web/packages/eva/index.html](https://cran.r-project.org/web/packages/eva/index.html)

The complete error message when installing from Bioconductor:
`ERROR: dependency ‘eva’ is not available for package ‘waddR’`

The complete error message when installing from Git repository:
```
Erreur : Failed to install 'waddR' from GitHub:
  (converti depuis l'avis) package ‘eva’ is not available (for R version 3.6.2)
```
Thank you very much in advance for your help.
Looking forward to give waddR a try!

**Comment by JulianFlesch** [comment]
Hi Yoann,

Thanks you for trying out waddR :)
I have contacted the guys at _eva_ and proposed changes that would fix both our packages.
For the meantime I will try to supply a patch, that allows us to be independent of them. I will inform you here, once this is available on the development branch of Bioconductor.

**Comment by JulianFlesch** [comment]
A patch is now available in the RELEASE of Bioconductor, that fixes this issue.

**Comment by YoannPa** [comment]
Thanks a lot Julian !
I am able to install the package now.
Best !
